server:
  port: 8085

spring:
  config:
    import:
      - optional:file:./config/application-secret.yml
      - optional:file:../config/application-secret.yml

  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
      password: ${redis.password}

  ai:
    openai:
      api-key: ${ai.api-key}
      base-url: ${ai.base-url}
      chat:
        options:
          model: ${ai.chat-model:qwen3.7-plus}
          temperature: 0.7

# 和风天气
qweather:
  host: ${qweather.host}
  api-key: ${qweather.api-key}